import type { NextPage } from 'next'
import Head from 'next/head'
import { Hero } from '@components/Hero'
import { PreAbout } from '@components/PreAbout'
import { Skills } from '@components/Skills'
import { Experience } from '@components/Experience'
import { Education } from '@components/Education'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <PreAbout/>
      <Skills/>
      <Experience/>
      <Education/>
    </>
  )
}

export default Home
